services:
    client:
        build:
            context: ./client
            args:
                - VITE_VIVA_URL=${VITE_VIVA_URL}
        ports:
            - "5173:5173"
        depends_on:
            - server
        env_file:
            - .env
        environment:
            - VITE_VIVA_URL=${VITE_VIVA_URL}

    server:
        build:
            context: ./server
        ports:
            - "3000:3000"
        env_file:
            - .env
        volumes:
            - ./server/logs:/app/logs
