services:
    client:
        build:
            context: ./client
        ports:
            - "5173:5173"
        depends_on:
            - server

    server:
        build:
            context: ./server
        ports:
            - "3000:3000"
        env_file:
            - .env
        volumes:
            - ./server/logs:/app/logs
