import { API } from "@onslip/onslip-360-node-api";

export const integrationConfig: {
    integration: API.Integration;
} = {
    integration: {
        alias: "kevtehdev444445",
        name: "Kiosken Integration (Kevtehdev444445)",
        type: "oauth",
        description: "Integration för Kiosken",
        author: "Kevin Johnson",
        email: "kevtehdev@dev201480",
        "web-address": "http://localhost:5173",

        categories: ["orders", "sales", "payments", "stock-balances"],

        permissions: [
            "rebuild-db-index",
            "send-emails",
            "show-daily-password",
            "show-buttons",
            "edit-buttons",
            "show-button-maps",
            "edit-button-maps",
            "show-companies",
            "edit-companies",
            "edit-company-info",
            "terminate-company",
            "show-company-config",
            "edit-company-config",
            "show-integrations",
            "edit-integrations",
            "use-integrations",
            "admin-integrations",
            "show-labels",
            "edit-labels",
            "show-records",
            "add-external-records",
            "add-records",
            "edit-records",
            "show-product-groups",
            "edit-product-groups",
            "show-products",
            "edit-products",
            "show-tabs",
            "edit-tabs",
            "show-tills",
            "edit-tills",
            "bind-tills",
            "bind-control-unit",
            "edit-till-config",
            "show-users",
            "edit-users",
            "edit-personal-info",
            "show-customers",
            "edit-customers",
            "show-certs",
            "add-certs",
            "edit-certs",
            "show-locations",
            "edit-locations",
            "show-accounts",
            "edit-accounts",
            "show-payment-methods",
            "edit-payment-methods",
            "show-vouchers",
            "use-vouchers",
            "edit-vouchers",
            "admin-vouchers",
            "show-roles",
            "edit-roles",
            "show-trigger-events",
            "edit-trigger-events",
            "admin-trigger-events",
            "run-report-jobs",
            "show-triggers",
            "edit-triggers",
            "use-triggers",
            "show-access-tokens",
            "edit-access-tokens",
            "use-access-tokens",
            "admin-access-tokens",
            "show-peripherals",
            "edit-peripherals",
            "show-stock-balances",
            "edit-stock-balances",
            "admin-stock-balances",
            "show-inventory-adjustments",
            "edit-inventory-adjustments",
            "show-resources",
            "edit-resources",
            "show-orders",
            "edit-orders",
            "show-campaigns",
            "edit-campaigns",
            "show-product-modifiers",
            "edit-product-modifiers",
            "show-priv-port-tokens",
            "edit-priv-port-tokens",
            "show-swish-transactions",
            "edit-swish-transactions",
            "use-swish-transactions",
            "admin-swish-transactions",
            "use-cloud-control-unit",
            "show-direct-marketing-campaigns",
            "admin-direct-marketing-campaigns",
            "edit-direct-marketing-campaigns",
            "send-direct-marketing-campaigns",
            "show-digital-receipt-receipients",
            "edit-digital-receipt-receipients",
            "show-digital-receipts",
            "edit-digital-receipts",
            "send-digital-receipts",
            "admin-system-config",
            "show-short-uris",
            "edit-short-uris",
            "use-pin-reset",
            "show-shifts",
            "edit-shifts",
            "admin-shifts",
            "use-shifts",
            "show-merchants",
            "edit-merchants",
            "show-company-summaries",
            "edit-company-summaries",
            "show-merchant-summaries",
            "show-mq-record-schedules",
            "edit-mq-record-schedules",
            "show-event-streams",
            "use-event-streams",
            "edit-event-streams",
            "use-weiq-payment-methods",
            // "add-external-records",
            // "use-access-tokens",
            // "show-products",
            // "show-product-groups",
            // "show-button-maps",
            // "show-campaigns",
            // "show-customers",
            // "show-resources",
            // "show-integrations",
            // "show-locations",
            // "show-orders",
            // "edit-orders",
            // "send-emails",
            // "show-digital-receipts",
            // "show-payment-methods",
            // "show-stock-balances",
            // "edit-records",
            // "show-records",
            // "edit-digital-receipts",
            // "show-digital-receipts",
            // "add-records",
            // "send-emails",
            // "send-digital-receipts",
            // "edit-customers",
            // "show-customers",
            // "show-payment-methods",
            // "edit-payment-methods",
            // "edit-labels",
            // "show-labels",
        ],

        // Features måste vara tomma eller innehålla bara de features som är explicit definierade i API:et
        features: ["campaigns", "stock-balances", "external-journal"],

        confinements: ["location"],

        "oauth-redirect-uris": ["http://localhost:3000/api/oauth/callback"],
    },
};
